### ISSUE TITLE
Splitting Algorithms into Stages

### ISSUE THREAD

**Issue by alexmorley** [flatironinstitute/spikesortercomparison#6]
Hey, Just read through the text, this is a really cool project! I just wanted to provide a nudge towards keeping it possible (even if it isn't a feature present at the start) to benchmark each step of the algorithm separately.

Why?
Non-clustering steps can have a massive impact on the results, and there is a lot of overlap in the steps involved in each algorithm. Furthermore, comparisons of clustering mean much less (at least to me) if you don't know why one is working better than the other.

How?
There are two obvious complexities here, one is that not all algorithms define the same "typical" set of steps for spike-sorting (e.g. signal pre-processing, spike detection, feature extraction, clustering, +misc post-clustering steps). The first problem we can solve by explicitly noting for each algorithm all of its intermediate-points (e.g. for MSort & Klusta we know that we can have all of the initial spike-times, wave-forms, features etc.) so that we know for this pair of algorithms we can compare the performance of the actual clustering step as well as all the others. Where algorithms only have one endpoint in common (i.e. the final sorted spike-times) then that's all that needs to be compared.

The other issue is that even where they do have the same stages as above, not all the software writes each of these outputs into a sensibly formatted file that we can save. This I think is difficult to work around, but forking projects/persuading authors to add an extra few lines to save these intermediate outputs isn't impossible.

The two main steps I think this is super important for is spike-detection and feature extraction. If algorithms provide "snippet sorting" I think that's a good place to start.

**Comment by magland** [comment]
Thanks for those insights, Alex M.. I think we can do this without disrupting too much our philosophy of black-box sorting (see below). Alex B., please let me know what you think.

The primary interface (as described in the white paper draft) relates to black-box spike sorters that take input raw timeseries and spit out times/labels/(channels). But in addition we can then have additional interfaces -- for example preprocessing which maps (timeseries)->(timeseries). For example we can separately wrap mountainsort3 and mountainsort3-preprocessing. Thus we do not impose the requirement of a spike sorting algorithm to be a collection of steps. Procedures/pipelines that implement the preprocessing interface can be validated in a different way.

Another possibility is snippet spike sorters (which is useful in its own right because sometimes that's the data the labs have collected)

A possibility for the list of interfaces
black-box-spike-sorting
preprocessing
detection
snippet-spike-sorting

Of course once can pair preprocessing->detection->snippet-spike-sorting to create a black-box-spike-sorting pipeline, but perhaps only some algorithms would do this.

Incidentally, MountainSort cannot easily be broken down into separate detection/snippet-sorting steps.

**Comment by ahbarnett** [comment]
Dear Alex & Jeremy,
These are interesting ideas, but I think it shouldn't distract us from spending the next couple of months benchmarking complete spike sorters. The major packages don't allow a clean split (eg JRClust cannot be split to a clip clustering because it uses time-spacings between snippets). Even snippet-based sorting has the issue whether time info is allowed or not. And it prohibits studying the overlapping case. I think in order to study drift and collisions we must benchmark the whole setup.
Best,  Alex

**Comment by alexmorley** [comment]
For sure. I understand that starting off with the full setup is a job enough in itself! 
Cheers, A
