### ISSUE TITLE
Comments on white paper

### ISSUE THREAD

**Issue by agiovann** [flatironinstitute/spikesortercomparison#7]
## Section 2.1
- column-major order, why? Is it because this is the way data is collected? It is not the way you will access the data most of the times for computing purposes.
- json is probably the way to go, human and machine readable
- spelling mistake, sitation -> situation

## Section 2.2
- why not using binary format here as well instead of  MDA or HDF5?

## Section 2.4
- hosting the algorithm seems a major effort, only hosting ground truth is already a giant first step
- the docker file idea might alleviate the point above

## Section 3
- it would be resource consuming but one might think about generating ground truth the way we did for CaImAn (like in [3]?). Three humans each selecting neurons with some interface (the difficulty there is that manually selecting neurons is impossible for you, is it?) 

## Equation 3-6
- Why not using precision, recall and f1-score?

## Quality metrics
- "Is cluster shape agnostic"" --> is that a question?

**Comment by ahbarnett** [comment]
Hi Andrea - thanks for the comments.
Since we already run the 3-4 major algs we will host those, but allow people to upload their own sortings too.

Re Eqn 3-6 I will relate these metrics to precision, recall ,and F-measure (is that what you mean by f1-score?)

"Is cluster shape agnostic" is a statement - will clarify.

Cheers, Alex
